# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
#version: 2.1
# Use a package of configuration called an orb.
#orbs:
  # Declare a dependency on the welcome-orb
#  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
#workflows:
  # Name the workflow "welcome"
 # welcome:
    # Run the welcome/run job in its own container
  #  jobs:
   #   - welcome/run

version: 2.1

#workflows:
jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      #- checkout
      - run: echo  "HELLLLLOOOOO WWWWOOOOOOORRRRLLLLLLD" > output.txt
      - persist_to_workspace:
          root: /myworkspace
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - persist_to_workspace:
          root: /myworkspace
          paths:
            - output.txt
      - run: cat  output.txt
